### ISSUE TITLE
Tried on actual Luggage?

### ISSUE THREAD

**Issue by Gnagha** [Xyl2k/TSA-Travel-Sentry-master-keys#17]
Did anyone of you ever tried to use the keys on actual luggage locks? I made a 007-Key and it works well with a padlock, but it didn't with a suitcase lock. Any ideas?

**Comment by MS3FGX** [comment]
You mean a TSA lock integrated into a piece of luggage rather than being external? Now that you mention it, no, I haven't seen anyone test with that. Probably because we all just went out and bought some cheap TSA locks to start testing/working with. Personally, I don't even own any luggage, and haven't been on a plane in 20+ years. 

Anyway, why doesn't it work? Does it not fit, or does it not turn?

**Comment by Gnagha** [comment]
I don't really know, why it didn't work.

I tried it on actual luggage. While my external locks work fine with these keys, these integrated locks didnt open. After quiet a while the 002 key worked, but it was quiet difficult. Much jiggling was needed and a lot of strenght. The 007 key didn't work at all while it works like an original key on the external locks.

The keys fit in, but I wasn't able to turn. I was frightened to break them.

**Comment by johnnyxmas** [comment]
The following may be helpful:

*Dimensions in mm of the key blade for the stock key. If you have a caliper handy, using this would be excellent. At the very least, a picture of the key next to a metric ruler. 

*Picture of the stock key next to the printed one

*Confirmation that the key you printed is within .1mm of the original file. Again, caliper.

**Comment by iandotmartin** [comment]
I can confirm the TSA 002 opened the lock successfully after some initial difficulty. I should be able to post measurements/pictures in the next few days.

**Comment by Gnagha** [comment]
Can you post the measurements? I wanted to print some keys later again. So I could try them.
