### ISSUE TITLE
key no.2

### ISSUE THREAD

**Issue by Mannmaan** [Xyl2k/TSA-Travel-Sentry-master-keys#26]

**Comment by Mannmaan** [comment]
Recently the stupid TSA "unlock" my luggage in Orlando and did not turn to "Lock" position after they check  my Tumi Luggage that happen to have TSA0002 key on the locking system.
so in my search for the key, i came across this article and did 3D printed TSA0002 with the file provided. 
but im facing a problem, the key doesn't even fit in the insert. please advise or can someone send other link.
thanks

**Comment by MS3FGX** [comment]
The 2 key is generally known to work, so there's a good chance the issue is in the printer calibration. 

Is the key too wide, or too thick? If it's too thick I'd start by trying to sand the top side down a bit untill it fits. If it's too wide, you should measure it with calipers to see how far off it is compared to the target dimensions. 

You can also try scaling down the problem dimension in your slicer. For example if the keys are coming out too thick, you might try setting the Z scale to .98 - .95.

**Comment by Mannmaan** [comment]
thanks for your advise, it appear to be too wide. i will try to scale down.

**Comment by johnnyxmas** [comment]
Yes, the manufacturing tolerances of locks have been found to be surprisingly lenient, so a need to adjust the width of printed keys is to be expected on occasion. Also be aware the plastic expands & contracts due to environmental effects, so it may take several tries and some tweaking to get a key that works. 

Thanks,

JohnnyXmas | @j0hnnyxm4s
~~*\Sent while mobile/*~~

**Comment by Mannmaan** [comment]
Thanks Johnnyxmas. plastic expedition due to environmental make a lot of sense since i live in Jakarta Indonesia. it very very hot and high humidity down here.
