### ISSUE TITLE
What printer head is recommended?

### ISSUE THREAD

**Issue by vincentcox** [Xyl2k/TSA-Travel-Sentry-master-keys#35]
Because of the fine size of the keys, what size of the printer head is recommended? And which printing material to avoid getting the smaller printer head clogged

**Comment by MS3FGX** [comment]
I assume you mean nozzle. Personally I did everything with standard 0.4 mm nozzle in PLA.

A smaller nozzle is always nice for greater detail, but at least for the major keys (2/7), the details aren't particularly fine to begin with. That, plus the locks themselves are sloppy enough that you really only need to get close.

**Comment by johnnyxmas** [comment]
I wouldn't recommend using FDM printers at all for this minute work, though it's been confirmed to be possible. Use the finest possible head and layer height your printer supports, and apply a whole lot of hope. I'd recommend SLA or SLS printers instead due to their resistance to environmental variables and increased resolutions. 

Overall, this is outside of the scope of this project. The files here are an accurate recreation of the real keys, but accurately recreating them on an FDM printer has so many variables outside of the files' control that we can't do anything about it here. Please only open issues that relate to the accuracy of the files.
